name: CI

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: -Dwarnings
  RUSTDOCFLAGS: -Dwarnings
  MSRV: "1.72"
  CRATES_LIST: "iroh,iroh-bytes,iroh-gossip,iroh-metrics,iroh-net,iroh-sync,iroh-test"

jobs:
  build_and_test_nix:
    timeout-minutes: 30
    name: Build and test (Nix)
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        name: [ubuntu-latest, macOS-arm-latest]
        rust: [nightly, stable]
        include:
          - name: ubuntu-latest
            os: ubuntu-latest
            release-os: linux
            release-arch: amd64
            runner: [self-hosted, linux, X64]
          - name: macOS-arm-latest
            os: macOS-latest
            release-os: darwin
            release-arch: aarch64
            runner: [self-hosted, macOS, ARM64]
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Install ${{ matrix.rust }}
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
    
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3

    - name: tests (all features)
      run: |
        for i in ${CRATES_LIST//,/ }
        do
          cargo test -p $i --all-features --lib --bins --tests
        done
      env:
        RUST_LOG: ${{ runner.debug && 'DEBUG' || 'INFO'}}
      
    - name: tests (no features)
      run: |
        for i in ${CRATES_LIST//,/ }
        do
          cargo test -p $i --no-default-features --lib --bins --tests
        done
      env:
        RUST_LOG: ${{ runner.debug && 'DEBUG' || 'INFO'}}

    - name: tests (default features)
      run: |
        for i in ${CRATES_LIST//,/ }
        do
          cargo test -p $i --lib --bins --tests
        done
      env:
        RUST_LOG: ${{ runner.debug && 'DEBUG' || 'INFO'}}

    - name: doctests
      run: |
        for i in ${CRATES_LIST//,/ }
        do
          cargo test -p $i --all-features --doc
        done
      env:
        RUST_LOG: ${{ runner.debug && 'DEBUG' || 'INFO'}}
      
  build_and_test_windows:
    timeout-minutes: 30
    name: Build and test (Windows)
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        name: [windows-latest]
        rust: [nightly, stable]
        target:
          - x86_64-pc-windows-msvc
        include:
          - name: windows-latest
            os: windows
            runner: [self-hosted, windows, x64]
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Install ${{ matrix.rust }}
      run: |
        rustup toolchain install ${{ matrix.rust }}
        rustup toolchain default ${{ matrix.rust }}
        rustup target add ${{ matrix.target }}
        rustup set default-host ${{ matrix.target }}
    
    - uses: msys2/setup-msys2@v2

    - name: tests (all features)
      run: cargo test --workspace --all-features --lib --bins --tests --target ${{ matrix.target }}
      env:
        RUST_LOG: ${{ runner.debug && 'DEBUG' || 'INFO'}}

    - name: tests (no features)
      run: cargo test --workspace --no-default-features --lib --bins --tests --target ${{ matrix.target }}
      env:
        RUST_LOG: ${{ runner.debug && 'DEBUG' || 'INFO'}}
      
    - name: tests (default features)
      run: cargo test --workspace --lib --bins --tests --target ${{ matrix.target }}
      env:
        RUST_LOG: ${{ runner.debug && 'DEBUG' || 'INFO'}}

  build_release:
    timeout-minutes: 60
    name: Build release binaries
    runs-on: ${{ matrix.runner }}
    continue-on-error: false
    needs: build_and_test_nix
    if: ${{ always() && github.ref_name=='main' }}
    strategy:
      fail-fast: false
      matrix:
        name: [ubuntu-latest, ubuntu-arm-latest, macOS-latest, macOS-arm-latest]
        rust: [stable]
        experimental: [false]
        include:
          - name: ubuntu-arm-latest
            os: ubuntu-latest
            release-os: linux
            release-arch: aarch64
            runner: [self-hosted, linux, ARM64]
          - name: ubuntu-latest
            os: ubuntu-latest
            release-os: linux
            release-arch: amd64
            runner: [self-hosted, linux, X64]
          - name: macOS-latest
            os: macOS-latest
            release-os: darwin
            release-arch: x86_64
            runner: [self-hosted, macOS, X64]
          - name: macOS-arm-latest
            os: macOS-latest
            release-os: darwin
            release-arch: aarch64
            runner: [self-hosted, macOS, ARM64]
          # - os: windows-latest
          #   release-os: windows
          #   release-arch: amd64
          #   runner: [windows-latest]
    env:
      RUST_BACKTRACE: full
      RUSTV: ${{ matrix.rust }}
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Set build arch
      run: |
        echo "RELEASE_ARCH=${{ matrix.release-arch }}" >> $GITHUB_ENV
        echo "RELEASE_OS=${{ matrix.release-os }}" >> $GITHUB_ENV

    - name: Install ${{ matrix.rust }}
      run: |
        rustup toolchain install ${{ matrix.rust }}
    
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3

    - name: build release
      run: |
        cargo build --profile optimized-release --all-features

    - name: Setup awscli on linux
      if: matrix.name == 'ubuntu-latest'
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update

    - name: Setup awscli on linux
      if: matrix.name == 'ubuntu-arm-latest'
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update

    - name: Setup awscli on mac
      if: matrix.os == 'macos-latest'
      run: |
        curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
        sudo installer -pkg AWSCLIV2.pkg -target /

    - name: Set aws credentials
      if: matrix.os != 'windows-latest'
      run: |
          echo "AWS_ACCESS_KEY_ID=${{secrets.S3_ACCESS_KEY_ID}}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{secrets.S3_ACCESS_KEY}}" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=us-west-2" >> $GITHUB_ENV

    - name: push release
      if: matrix.os != 'windows-latest'
      run: |
        aws s3 cp ./target/optimized-release/iroh s3://vorc/iroh-${RELEASE_OS}-${RELEASE_ARCH}-${GITHUB_SHA::7} --no-progress
        aws s3 cp ./target/optimized-release/derper s3://vorc/derper-${RELEASE_OS}-${RELEASE_ARCH}-${GITHUB_SHA::7} --no-progress

    - name: push release latest
      if: matrix.os != 'windows-latest'
      run: |
        aws s3 cp ./target/optimized-release/iroh s3://vorc/iroh-${RELEASE_OS}-${RELEASE_ARCH}-latest --no-progress
        aws s3 cp ./target/optimized-release/derper s3://vorc/derper-${RELEASE_OS}-${RELEASE_ARCH}-latest --no-progress

  cross:
    timeout-minutes: 30
    name: Cross compile
    runs-on: [self-hosted, linux, X64]
    strategy:
      fail-fast: false
      matrix:
        target:
          - i686-unknown-linux-gnu
          - armv7-linux-androideabi
          - aarch64-linux-android
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Install rust stable
      uses: dtolnay/rust-toolchain@stable

    - name: Cleanup Docker
      continue-on-error: true
      run: |
        docker kill $(docker ps -q)

    - name: Install cross
      # See https://github.com/cross-rs/cross/issues/1222
      run: cargo install cross --git https://github.com/cross-rs/cross

    - name: check
      run: cross check --all --target ${{ matrix.target }}
      env:
        RUST_LOG: ${{ runner.debug && 'DEBUG' || 'INFO'}}

    - name: test
      # cross tests are currently broken vor armv7 and aarch64
      # see https://github.com/cross-rs/cross/issues/1311
      if: matrix.target == 'i686-unknown-linux-gnu'
      run: cross test --all --target ${{ matrix.target }} -- --test-threads=12
      env:
        RUST_LOG: ${{ runner.debug && 'DEBUG' || 'INFO'}}

  check_fmt_and_docs:
    timeout-minutes: 30
    name: Checking fmt and docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt

    - name: fmt
      run: cargo fmt --all -- --check

    - name: Docs
      run: cargo doc --workspace --all-features --no-deps --document-private-items

  clippy_check:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    # Can be switched back once 1.75 lands
    # https://github.com/rust-lang/cargo/issues/12115#issuecomment-1768170381
    - uses: dtolnay/rust-toolchain@nightly
      with:
          components: clippy

    # TODO: We have a bunch of platform-dependent code so should
    #    probably run this job on the full platofrm matrix
    - name: clippy check (all features)
      run: cargo clippy --workspace --all-features --all-targets --bins --tests --benches

    - name: clippy check (no features)
      run: cargo clippy --workspace --no-default-features --lib --bins --tests

    - name: clippy check (default features)
      run: cargo clippy --workspace --all-targets

  msrv:
    timeout-minutes: 30
    name: Minimal Supported Rust Version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ env.MSRV }}

    - name: Check MSRV all features
      run: |
        cargo +$MSRV check --workspace --all-targets --features cli

  cargo_deny:
    timeout-minutes: 30
    name: cargo deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          arguments: --workspace --all-features
          command: check
          command-arguments: "-Dwarnings"

  netsim-integration-tests:
    timeout-minutes: 30
    name: Run network simulations/benchmarks
    runs-on: [self-hosted, linux, X64]
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: recursive
    
    - name: Install rust stable
      uses: dtolnay/rust-toolchain@stable

    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3

    - name: Build iroh
      run: |
        cargo build --release --workspace --all-features

    - name: Fetch and build chuck
      run: |
        cd ..
        rm -rf chuck
        git clone https://github.com/n0-computer/chuck.git
        cd chuck
        cargo build --release
    
    - name: Install netsim deps
      run: |
        cd ../chuck/netsim
        sudo apt update
        ./setup.sh

    - name: Copy binaries to right location
      run: |
        cp target/release/iroh ../chuck/netsim/bins/iroh
        cp target/release/derper ../chuck/netsim/bins/derper
        cp ../chuck/target/release/chuck ../chuck/netsim/bins/chuck

    - name: Run tests
      run: |
        cd ../chuck/netsim
        sudo kill -9 $(pgrep ovs) || true
        sudo mn --clean || true
        sudo python3 main.py ${{ runner.debug && '--debug' || ''}} --integration sims/iroh/iroh.json
        sudo python3 main.py ${{ runner.debug && '--debug' || ''}} --integration sims/integration
    - name: Cleanup
      run: |
        sudo kill -9 $(pgrep derper) || true
        sudo kill -9 $(pgrep iroh) || true
        sudo kill -9 $(pgrep ovs) || true
        sudo mn --clean || true
        
    - name: Setup Environment (PR)  
      if: ${{ github.event_name == 'pull_request' }}  
      shell: bash  
      run: |  
        echo "LAST_COMMIT_SHA=$(git rev-parse --short ${{ github.event.pull_request.head.sha }})" >> ${GITHUB_ENV}
        echo "HEAD_REF=${{ github.event.pull_request.head.ref }}" >> ${GITHUB_ENV}
    - name: Setup Environment (Push)  
      if: ${{ github.event_name == 'push' || github.event_name == 'merge_group' }}  
      shell: bash  
      run: |  
        echo "LAST_COMMIT_SHA=$(git rev-parse --short ${GITHUB_SHA})" >> ${GITHUB_ENV}
        echo "HEAD_REF=${{ github.head_ref }}" >> ${GITHUB_ENV}

    - name: Generate reports
      run: |
        cd ../chuck/netsim
        python3 reports_csv.py --prom --commit ${{ env.LAST_COMMIT_SHA }} > report_prom.txt
        python3 reports_csv.py --metro --commit ${{ env.LAST_COMMIT_SHA }} > report_metro.txt
        python3 reports_csv.py --metro --integration --commit ${{ env.LAST_COMMIT_SHA }} > report_metro_integration.txt

    - name: Dump report
      if: ${{ (github.event.pull_request && !github.event.pull_request.head.repo.fork) || !github.event.pull_request }}
      run: |
        export AWS_ACCESS_KEY_ID=${{secrets.S3_ACCESS_KEY_ID}}
        export AWS_SECRET_ACCESS_KEY=${{secrets.S3_ACCESS_KEY}}
        export AWS_DEFAULT_REGION=us-west-2
        
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -q awscliv2.zip
        sudo ./aws/install --update

        cd ../chuck/netsim

        aws_fname=intg_${{ env.LAST_COMMIT_SHA }}.tar.gz
        tar cvzf report.tar.gz report_prom.txt report_metro.txt report_metro_integration.txt logs/ report/ viz/
        aws s3 cp ./report.tar.gz s3://${{secrets.S3_REPORT_BUCKET}}/$aws_fname --no-progress

        link_data='dump{fname="'$aws_fname'",commit="'${{ env.LAST_COMMIT_SHA }}'",branch="'${{ env.HEAD_REF }}'"} 1.0'
        link_data=$(printf "%s\n " "$link_data")
        curl -X POST -H  "Content-Type: text/plain" --data "$link_data" ${{secrets.PROM_ENDPOINT}}/metrics/job/netsim/instance/${instance}

    - name: Echo metrics
      run: |
        cd ../chuck/netsim
        d=$(cat report_metro.txt)
        metro_data=$(printf "%s\n " "$d")
        echo "$metro_data" 
        d=$(cat report_metro_integration.txt)
        metro_data=$(printf "%s\n " "$d")
        echo "$metro_data" 
